In [2]:
import numpy as np

a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
a[1]

3

In [5]:
store_a = [20,10,30]
store_b = [70,90,70]

In [7]:
list_sum = store_a + store_b
list_sum

[20, 10, 30, 70, 90, 70]

In [8]:
np_store_a = np.array(store_a)
np_store_b = np.array(store_b)
array_sum = np_store_a + np_store_b
array_sum

array([ 90, 100, 100])

In [9]:
a = np.array([2,3,4])

a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [10]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
a = np.array([10, 20, 30])

In [13]:
b = np.array(1, 2, 3)
a+b

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
b = np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [15]:
b = np.array([1, 2, 3])

In [16]:
a+b

array([11, 22, 33])

In [17]:
a-b

array([ 9, 18, 27])

In [18]:
a/b

array([10., 10., 10.])